### ISSUE TITLE
UE4.27

### ISSUE THREAD

**Issue by ghost** [iwer/GeotiffLandscape#1]
Having trouble compiling for UE4.27 can you please advise?

**Comment by iwer** [comment]
Sure, what's the error you get?

**Comment by ghost** [comment]
Thank you so much for getting back to me so quickly.
To be honest the instructions were a bit over my head.
I added the binaries for GDAL to the project /plugins
I got stuck here…
***@***.***

Where does this go:
***@***.***

Creating Custom Modules | Orfeas Eleftheriou<https://www.orfeasel.com/creating-custom-modules/?unapproved=20795&moderation-hash=1d70213ce65efd4107cdd7c2cec740da#comment-20795>
I found this link but really not sure if its what I need?

Sorry I just don’t understand this level of the compiler..


Sincerely

Ben Hiron-Grimes

Director/Head of Innovation

The Excel Experts Ltd | The Old Church School | Butts Hill | Frome | BA11 1HR | 0800 772 3782 | Check out our latest work at: www.theexcelexperts.com
***@***.***

Co. Reg. No. 8455410 | Vat Reg. 290 6705 89
This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named.
If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this
e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any
action in reliance on the contents of this information is strictly prohibited and may constitute a criminal offence.

**Comment by iwer** [comment]
> I got stuck here…
> ***@***.***
> 
> Where does this go:
> ***@***.***

Well this does not tell me much...

But you mention GDAL Binaries, GDAL Binaries should actually come from https://github.com/TensorWorks/UnrealGDAL which uses a build wrapper to build the GDAL Libraries against UE4s Dependencies so that it works when linked in a project.

If you downloaded the Release v0.0.1 of UnrealGDAL it may well be that the release is not compatible with UE4.27 as it was released ~16month ago.

But to build it from source isn't that big of a deal using Adam Rehns ue4cli and conan-ue4cli: https://github.com/TensorWorks/UnrealGDAL#building-everything-from-source

Rebuild of Source Plugins will probably be necessary after each UE4 engine release.

**Comment by ghost** [comment]
Apologies I put in screen grabs but some reason you didn’t receive them.
Don’t’ worry if its all out of date, this is beyond me. There is a plugin called Terrapro that lets me import geotiff’s. I’ll use that instead.
Thanks anyway

Sincerely

Ben Hiron-Grimes

Director/Head of Innovation

The Excel Experts Ltd | The Old Church School | Butts Hill | Frome | BA11 1HR | 0800 772 3782 | Check out our latest work at: www.theexcelexperts.com
***@***.***

Co. Reg. No. 8455410 | Vat Reg. 290 6705 89
This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager. This message contains confidential information and is intended only for the individual named.
If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this
e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any
action in reliance on the contents of this information is strictly prohibited and may constitute a criminal offence.
