### ISSUE TITLE
modules missing error

### ISSUE THREAD

**Issue by Hiverize** [iwer/GeotiffLandscape#3]
I followed the instructions for usage (place plugin in engine plugins folder, write to .uproject and myproject.Build.cs), but I get the following error: 
Missing modules: The following modules are missing or built with a different engine version:
GeoReference
GeotiffLandscape
GeotiffLandscapeEditor

I used engine version 4.25.4 on windows. UnrealGDAL plugin is enabled.
Am I missing something?

**Comment by iwer** [comment]
I think, if you place code plugins into the Engine Plugin directory, you need to recompile the engine including those plugins. Of course this only works on a source build.

It is easier to put additional Plugins into a C++-Projects Plugin directory. Then you only have to recompile your project with the additional Plugins to get working modules for the current engine version.

Maybe I should clarify, that I mean the Projects Plugin directory in the instructions.
