### ISSUE TITLE
which ue version

### ISSUE THREAD

**Issue by ws2179416905** [iwer/GeotiffLandscape#4]
Which version should be used to run this plug-in?  I used 4.25 to find that the content of the plugin cannot be loaded.

**Comment by iwer** [comment]
I probably resaved the assets with 4.26 in an oversight. However there is only an example in the Content directory and nothing needed for functionality. The Landscape file formats and asset types are implemented in code and should work from 4.25 upwards.

You should be save to delete the Content UAssets in 4.25. You could then recreate the example map by importing the tif for landscape height and the s2glc for layer wheights.
