### ISSUE TITLE
Program crash problem

### ISSUE THREAD

**Issue by KSdong** [iwer/GeotiffLandscape#5]
Hi, thank you for sharing. But I have a problem. Can you give me some suggestions?

When I import an image, an error will appear after executing the following functions：

FLandscapeHeightmapInfo FLandscapeHeightmapFileFormat_Geotiff::Validate(const TCHAR* HeightmapFilename) const

Unhandled exception at0x00007FFF056515EF (UE4Editor-GeotiffLandscapeEditor.dll) (UE4Editor.exe 中）: 0xC0000005: Write into 0x000001DA568CACC0  An access conflict occurred。

----------------------------------------------------------------------------------------------
Have you ever encountered this problem？
Or can you tell me which part of the code should be executed after the function is executed under normal circumstances？

**Comment by iwer** [comment]
Hm, haven't encountered this in a while. Does the error message state a line number where the crash occurs?

[FLandscapeHeightmapFileFormat_Geotiff::Validate](https://github.com/iwer/GeotiffLandscape/blob/1347bcb250e446c924ee9bda226c1b520c91750f/Source/GeotiffLandscapeEditor/Private/Landscape/LandscapeFileFormatGeoTiff.cpp#L19) opens the file and performs some checks to verify it can be imported correctly. If that succeeds it should map the height values of the file to the landscape using the ::Import method.

A possible error source could be the geo-reference system of the file, as there are loads of them and i have concentrated on reference systems with units in meter.
