### ISSUE TITLE
UE5 Compatibility

### ISSUE THREAD

**Issue by KontainPluton** [iwer/GeotiffLandscape#8]
I'd like to use your plugin with Unreal 5.2. 
Since your plugin uses UnrealGDAL, I tried to follow the information on the following github gist : 
https://gist.github.com/iwer/fc4e34a2a491461d606d826b72664845

There are several things I didn't understand. For example, where are these scripts ?
```
./Setup.bat
./GenerateProjectFiles.bat
```

I tried other techniques to build UnrealGDAL but nothing worked. And I can't understand your gist. Would it be possible to have more information on how to compile your plugin and UnrealGDAL for UE5?

One solution would be to have UnrealGDAL precompiled for UE5. Do you still have this precompiled plugin? And if so, would it be possible to send it to me as a package?

**Comment by iwer** [comment]
> There are several things I didn't understand. For example, where are these scripts ?
> 
> ```
> ./Setup.bat
> ./GenerateProjectFiles.bat
> ```

These are part of the UE5 source distribution (https://docs.unrealengine.com/5.0/en-US/building-unreal-engine-from-source/).

This is needed, because the GDAL library, that is wrapped by UnrealGDAL needs to be compiled with the same compiler, UE5 is compiled with. 

I'd rather not become a distributor for packages from other authors sources, especially as it would mean maintaining packages for all supported UE versions, as the source distribution ships with a dedicated build chain that potentially changes over different versions.

**Comment by sg-12345** [comment]
@iwer Hi I downloaded ue 5.1.1 source and build it using conan-ue4cli just as your gist (https://gist.github.com/iwer/fc4e34a2a491461d606d826b72664845) did but i got  the following error : 

```
Discovering modules, targets and source code for project...
Compiled assembly file 'C:\Users\sguney\Documents\Unreal Projects\GIS\Intermediate\Build\BuildRules\GISModuleRules.dll' appears to be for a newer CLR version or is otherwise invalid. Unreal Build Tool will try to recompile this assembly now. (Exception: Could not load file or assembly 'C:\Users\sguney\Documents\Unreal Projects\GIS\Intermediate\Build\BuildRules\GISModuleRules.dll'. Format of the executable (.exe) or library (.dll) is invalid.)

C:\Users\sguney\Documents\Unreal Projects\GIS\Plugins\UnrealGDAL\Source\GDAL\GDAL.Build.cs(12,7): error CS0246: The type or namespace name 'Tools' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\sguney\Documents\Unreal Projects\GIS\Plugins\UnrealGDAL\Source\GDAL\GDAL.Build.cs(43,3): error CS0246: The type or namespace name 'JsonObject' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\sguney\Documents\Unreal Projects\GIS\Plugins\UnrealGDAL\Source\GDAL\GDAL.Build.cs(43,24): error CS0103: The name 'JsonObject' does not exist in the current context
C:\Users\sguney\Documents\Unreal Projects\GIS\Plugins\UnrealGDAL\Source\GDAL\GDAL.Build.cs(43,44): error CS0246: The type or namespace name 'FileReference' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\sguney\Documents\Unreal Projects\GIS\Plugins\UnrealGDAL\Source\GDAL\GDAL.Build.cs(56,3): error CS0246: The type or namespace name 'JsonObject' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\sguney\Documents\Unreal Projects\GIS\Plugins\UnrealGDAL\Source\GDAL\GDAL.Build.cs(56,21): error CS0103: The name 'JsonObject' does not exist in the current context
C:\Users\sguney\Documents\Unreal Projects\GIS\Plugins\UnrealGDAL\Source\GDAL\GDAL.Build.cs(56,41): error CS0246: The type or namespace name 'FileReference' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\sguney\Documents\Unreal Projects\GIS\Plugins\UnrealGDAL\Source\GDAL\GDAL.Build.cs(59,12): error CS0246: The type or namespace name 'JsonObject' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\sguney\Documents\Unreal Projects\GIS\Plugins\UnrealGDAL\Source\GDAL\GDAL.Build.cs(154,3): error CS0246: The type or namespace name 'JsonObject' could not be found (are you missing a using directive or an assembly reference?)
C:\Users\sguney\Documents\Unreal Projects\GIS\Plugins\UnrealGDAL\Source\GDAL\GDAL.Build.cs(154,22): error CS0103: The name 'JsonObject' does not exist in the current context
C:\Users\sguney\Documents\Unreal Projects\GIS\Plugins\UnrealGDAL\Source\GDAL\GDAL.Build.cs(154,42): error CS0246: The type or namespace name 'FileReference' could not be found (are you missing a using directive or an assembly reference?)

Expecting to find a type to be declared in a target rules named 'GISTarget'. This type must derive from the 'TargetRules' type defined by Unreal Build Tool.
```

**Comment by iwer** [comment]
I just discovered, that there is an effort to make UnrealGDAL UE5.3 compatible by [ssav7912](https://github.com/ssav7912/GDALforUE5) and then [wolfgangp](https://github.com/wolfgangp/GDALforUE5). While I have not yet found the time to test it, it may be a straw, for everyone struggling with this.

**Comment by KontainPluton** [comment]
I was able to use the version made by [ssav7912](https://github.com/ssav7912/GDALforUE5) and it works very well for Unreal 5.2 and Unreal 5.3. It's a good solution for bypassing the issue.
